'use client';

import { useState, useEffect } from 'react';
import { useRouter } from 'next/navigation';

interface Project {
  _id: string;
  name: string;
  status: string;
  startDate: string;
  endDate?: string;
  priority: string;
}

interface Task {
  _id: string;
  title: string;
  description: string;
  status: 'todo' | 'in-progress' | 'completed';
  priority: 'low' | 'medium' | 'high';
  projectId: {
    _id: string;
    name: string;
  };
  assignedTo?: {
    _id: string;
    firstName: string;
    lastName: string;
    username: string;
  };
  dueDate?: string;
  estimatedHours?: number;
}

interface User {
  id: string;
  username: string;
  email: string;
  firstName: string;
  lastName: string;
  role: 'admin' | 'team_leader' | 'member';
  teamName?: string;
}

interface CalendarEvent {
  id: string;
  title: string;
  start: Date;
  end?: Date;
  type: 'project' | 'task';
  status: string;
  priority: string;
  assignee?: string;
  project?: string;
  projectDescription?: string;
}

export default function CalendarPage() {
  const [events, setEvents] = useState<CalendarEvent[]>([]);
  const [projects, setProjects] = useState<Project[]>([]);
  const [tasks, setTasks] = useState<Task[]>([]);
  const [loading, setLoading] = useState(true);
  const [user, setUser] = useState<User | null>(null);
  const [currentDate, setCurrentDate] = useState(new Date());
  const [selectedEvent, setSelectedEvent] = useState<CalendarEvent | null>(null);
  const [viewType, setViewType] = useState<'month' | 'week' | 'day'>('month');
  const [filterType, setFilterType] = useState<'all' | 'projects' | 'tasks'>('all');
  const router = useRouter();

  useEffect(() => {
    // Public calendar - no authentication required
    fetchCalendarData();
  }, []);

  // Generate events whenever projects or tasks change
  useEffect(() => {
    if (projects.length > 0 || tasks.length > 0) {
      generateCalendarEvents();
    }
  }, [projects, tasks]);

  // Remove authentication check for public calendar
  // const checkAuth = async () => {
  //   try {
  //     const response = await fetch('/api/auth/user');
  //     if (!response.ok) {
  //       router.push('/login');
  //       return;
  //     }
  //     const userData = await response.json();
  //     setUser(userData);
  //   } catch (error) {
  //     console.error('Auth check failed:', error);
  //     router.push('/login');
  //   }
  // };

  const fetchCalendarData = async () => {
    try {
      setLoading(true);
      
      // Fetch public projects data (no authentication required)
      const projectsResponse = await fetch('/api/public/projects?limit=100', {
        headers: {
          'Content-Type': 'application/json',
        },
      });

      if (projectsResponse.ok) {
        const projectsData = await projectsResponse.json();
        setProjects(projectsData.data || []);
      } else {
        console.error('Failed to fetch public projects:', projectsResponse.status);
      }

      // Fetch public tasks data (ongoing tasks with deadlines)
      const tasksResponse = await fetch('/api/public/tasks?limit=100', {
        headers: {
          'Content-Type': 'application/json',
        },
      });

      if (tasksResponse.ok) {
        const tasksData = await tasksResponse.json();
        setTasks(tasksData.data || []);
      } else {
        console.error('Failed to fetch public tasks:', tasksResponse.status);
        setTasks([]);
      }

      // Data fetching complete - events will be generated by useEffect
    } catch (error) {
      console.error('Error fetching calendar data:', error);
    } finally {
      setLoading(false);
    }
  };

  const generateCalendarEvents = () => {
    const calendarEvents: CalendarEvent[] = [];

    // Add project events
    let projectsWithDates = 0;
    projects.forEach((project, index) => {
      if (project.startDate) {
        projectsWithDates++;
        calendarEvents.push({
          id: `project-${project._id}`,
          title: `📋 ${project.name}`,
          start: new Date(project.startDate),
          end: project.endDate ? new Date(project.endDate) : undefined,
          type: 'project',
          status: project.status,
          priority: project.priority,
          project: project.name
        });
      }
      
      // Add deadline events as separate events
      const projectWithDeadline = project as any;
      if (projectWithDeadline.deadline && (!project.endDate || projectWithDeadline.deadline.getTime() !== new Date(project.endDate).getTime())) {
        calendarEvents.push({
          id: `deadline-${project._id}`,
          title: `⚠️ ${project.name} (Deadline)`,
          start: new Date(projectWithDeadline.deadline),
          type: 'project',
          status: project.status,
          priority: project.priority,
          project: project.name
        });
      }
    });

    // Add task events
    let tasksWithDates = 0;
    tasks.forEach((task, index) => {
      if (task.dueDate) {
        tasksWithDates++;
        const taskData = task as any; // Handle the type mismatch
        calendarEvents.push({
          id: `task-${task._id}`,
          title: `✓ ${task.title}`,
          start: new Date(task.dueDate),
          type: 'task',
          status: task.status,
          priority: task.priority,
          assignee: taskData.assignedTo ? `${taskData.assignedTo.firstName} ${taskData.assignedTo.lastName}` : 'Unassigned',
          project: taskData.project?.name || 'Unknown Project',
          projectDescription: taskData.project?.description || 'No description available for this project'
        });
      }
    });

    setEvents(calendarEvents);
  };

  useEffect(() => {
    generateCalendarEvents();
  }, [projects, tasks]);

  const getDaysInMonth = (date: Date) => {
    const year = date.getFullYear();
    const month = date.getMonth();
    const firstDay = new Date(year, month, 1);
    const lastDay = new Date(year, month + 1, 0);
    const daysInMonth = lastDay.getDate();
    const startDate = new Date(firstDay);
    startDate.setDate(startDate.getDate() - firstDay.getDay());
    
    const days = [];
    for (let i = 0; i < 42; i++) {
      days.push(new Date(startDate.getTime() + i * 24 * 60 * 60 * 1000));
    }
    return days;
  };

  const getEventsForDate = (date: Date) => {
    const filtered = events.filter(event => {
      const eventDate = new Date(event.start);
      const targetDate = new Date(date);
      
      // Check if it's a multi-day project
      if (event.type === 'project' && event.end) {
        return targetDate >= new Date(event.start) && targetDate <= new Date(event.end);
      }
      
      // For single day events
      const matches = eventDate.toDateString() === targetDate.toDateString();
      return matches;
    }).filter(event => {
      if (filterType === 'all') return true;
      if (filterType === 'projects') return event.type === 'project';
      if (filterType === 'tasks') return event.type === 'task';
      return true;
    });
    
    return filtered;
  };

  const getStatusColor = (status: string, type: string) => {
    if (type === 'project') {
      const colors = {
        'not-yet-started': 'bg-gray-200 text-gray-800',
        'on-going': 'bg-blue-200 text-blue-800',
        'submitted': 'bg-yellow-200 text-yellow-800',
        'approved': 'bg-green-200 text-green-800'
      };
      return colors[status as keyof typeof colors] || 'bg-gray-200 text-gray-800';
    } else {
      const colors = {
        'todo': 'bg-red-200 text-red-800',
        'in-progress': 'bg-yellow-200 text-yellow-800',
        'completed': 'bg-green-200 text-green-800'
      };
      return colors[status as keyof typeof colors] || 'bg-gray-200 text-gray-800';
    }
  };

  const getPriorityIcon = (priority: string) => {
    switch (priority) {
      case 'high': return '🔴';
      case 'medium': return '🟡';
      case 'low': return '🟢';
      default: return '⚪';
    }
  };

  const navigateMonth = (direction: number) => {
    const newDate = new Date(currentDate);
    newDate.setMonth(newDate.getMonth() + direction);
    setCurrentDate(newDate);
  };

  const formatDate = (date: Date) => {
    return date.toLocaleDateString('en-US', { 
      weekday: 'long', 
      year: 'numeric', 
      month: 'long', 
      day: 'numeric' 
    });
  };

  if (loading) {
    return (
      <div className="min-h-screen bg-gradient-to-br from-gray-50 via-white to-gray-100 flex items-center justify-center">
        <div className="text-center">
          <div className="animate-spin rounded-full h-12 w-12 border-b-2 border-amber-600 mx-auto"></div>
          <p className="mt-4 text-gray-600">Loading calendar...</p>
        </div>
      </div>
    );
  }

  return (
    <div className="min-h-screen bg-gradient-to-br from-gray-50 via-white to-gray-100">
      {/* Compact Header */}
      <div className="bg-white shadow-sm border-b border-gray-200">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-4">
          <div className="flex flex-col sm:flex-row sm:items-center sm:justify-between">
            <div>
              <h1 className="text-2xl font-bold text-gray-900">Public Project Calendar</h1>
              <p className="mt-1 text-sm text-gray-600">Transparency portal showing active project schedules and deadlines</p>
            </div>
            <div className="mt-3 sm:mt-0">
              <button
                onClick={() => router.push('/dashboard')}
                className="text-amber-600 hover:text-amber-800 font-medium text-sm"
              >
                ← Back to Dashboard
              </button>
            </div>
          </div>
        </div>
      </div>

      {/* Compact Calendar Controls */}
      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-4">
        <div className="bg-white rounded-lg shadow-sm border border-gray-200 p-4">
          <div className="flex flex-col sm:flex-row sm:items-center sm:justify-between gap-3">
            <div className="flex items-center space-x-3">
              <button
                onClick={() => navigateMonth(-1)}
                className="p-1.5 rounded-md border border-gray-300 hover:bg-gray-50 text-sm"
              >
                ←
              </button>
              <h2 className="text-lg font-semibold text-gray-900">
                {currentDate.toLocaleDateString('en-US', { month: 'long', year: 'numeric' })}
              </h2>
              <button
                onClick={() => navigateMonth(1)}
                className="p-1.5 rounded-md border border-gray-300 hover:bg-gray-50 text-sm"
              >
                →
              </button>
              <button
                onClick={() => setCurrentDate(new Date())}
                className="px-3 py-1.5 bg-amber-600 text-white rounded-md hover:bg-amber-700 text-sm"
              >
                Today
              </button>
            </div>

            <div>
              <select
                value={filterType}
                onChange={(e) => setFilterType(e.target.value as any)}
                className="px-3 py-1.5 border border-gray-300 rounded-md focus:ring-1 focus:ring-amber-500 text-sm"
              >
                <option value="all">All Events</option>
                <option value="projects">Projects Only</option>
                <option value="tasks">Tasks Only</option>
              </select>
            </div>
          </div>
        </div>

        {/* Prominent Calendar Grid */}
        <div className="bg-white rounded-lg shadow-sm border border-gray-200 overflow-hidden">
          {/* Calendar Header */}
          <div className="grid grid-cols-7 bg-gray-50 border-b border-gray-200">
            {['Sun', 'Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat'].map(day => (
              <div key={day} className="p-3 text-center font-semibold text-gray-700 text-sm">
                {day}
              </div>
            ))}
          </div>

          {/* Calendar Days */}
          <div className="grid grid-cols-7">
            {getDaysInMonth(currentDate).map((date, index) => {
              const dayEvents = getEventsForDate(date);
              const isCurrentMonth = date.getMonth() === currentDate.getMonth();
              const isToday = date.toDateString() === new Date().toDateString();

              return (
                <div
                  key={index}
                  className={`min-h-[180px] p-2 border-r border-b border-gray-200 ${
                    !isCurrentMonth ? 'bg-gray-50 text-gray-400' : 'bg-white'
                  } ${isToday ? 'bg-amber-50 border-amber-200' : ''}`}
                >
                  <div className={`text-sm font-medium mb-1 ${isToday ? 'text-amber-600' : ''}`}>
                    {date.getDate()}
                  </div>
                  
                  {/* Event List with All Tasks Displayed */}
                  <div className="space-y-1">
                    {dayEvents.map((event) => (
                      <div
                        key={event.id}
                        onClick={() => setSelectedEvent(event)}
                        className={`text-xs px-1.5 py-0.5 rounded cursor-pointer hover:opacity-75 ${getStatusColor(event.status, event.type)} border border-opacity-30`}
                        title={`${event.title} - ${event.project || 'No project'} - ${event.assignee || 'No assignee'}`}
                      >
                        <div className="font-bold text-[10px] leading-tight mb-0.5">
                          📋 {event.project || 'Unknown Project'}
                        </div>
                        <div className="text-[9px] opacity-80 leading-tight font-medium">
                          {event.title}
                        </div>
                        {event.assignee && (
                          <div className="text-[8px] opacity-70 leading-tight">
                            👤 {event.assignee}
                          </div>
                        )}
                      </div>
                    ))}
                  </div>
                </div>
              );
            })}
          </div>
        </div>
      </div>

      {/* Event Detail Modal */}
      {selectedEvent && (
        <div className="fixed inset-0 bg-black bg-opacity-50 flex items-center justify-center p-4 z-50">
          <div className="bg-white rounded-xl shadow-xl max-w-lg w-full p-6">
            <div className="flex justify-between items-start mb-4">
              <h3 className="text-xl font-bold text-gray-900">📋 {selectedEvent.project || 'Unknown Project'}</h3>
              <button
                onClick={() => setSelectedEvent(null)}
                className="text-gray-400 hover:text-gray-600"
              >
                ✕
              </button>
            </div>
            
            <div className="space-y-4">
              {/* Project Description */}
              {selectedEvent.projectDescription && (
                <div className="bg-blue-50 p-4 rounded-lg">
                  <h4 className="font-semibold text-gray-700 mb-2">Project Description</h4>
                  <p className="text-sm text-gray-600 leading-relaxed">
                    {selectedEvent.projectDescription}
                  </p>
                </div>
              )}

              {/* Task Information */}
              <div className="border-t pt-4">
                <h4 className="font-semibold text-gray-700 mb-3">Task Details</h4>
                
                <div className="space-y-3">
                  <div className="flex items-center space-x-3">
                    <span className="text-sm font-medium text-gray-600">Task:</span>
                    <span className="text-sm">{selectedEvent.title.replace('✓ ', '')}</span>
                  </div>

                  <div className="flex items-center space-x-3">
                    <span className="text-sm font-medium text-gray-600">Due Date:</span>
                    <span className="text-sm">{formatDate(selectedEvent.start)}</span>
                  </div>

                  <div className="flex items-center space-x-3">
                    <span className="text-sm font-medium text-gray-600">Status:</span>
                    <span className={`px-2 py-1 rounded-full text-xs font-medium ${getStatusColor(selectedEvent.status, selectedEvent.type)}`}>
                      {selectedEvent.status}
                    </span>
                  </div>

                  <div className="flex items-center space-x-3">
                    <span className="text-sm font-medium text-gray-600">Priority:</span>
                    <span className="flex items-center space-x-1">
                      <span>{getPriorityIcon(selectedEvent.priority)}</span>
                      <span className="text-sm">{selectedEvent.priority}</span>
                    </span>
                  </div>

                  {selectedEvent.assignee && (
                    <div className="flex items-center space-x-3">
                      <span className="text-sm font-medium text-gray-600">Assigned to:</span>
                      <span className="text-sm">👤 {selectedEvent.assignee}</span>
                    </div>
                  )}
                </div>
              </div>
            </div>

            <div className="mt-6 flex justify-end">
              <button
                onClick={() => setSelectedEvent(null)}
                className="px-4 py-2 bg-blue-600 text-white rounded-lg hover:bg-blue-700"
              >
                Close
              </button>
            </div>
          </div>
        </div>
      )}
    </div>
  );
}